id = "vue 2"
name = "Vue 2"
description = "Vue support with vetur."
version = "0.0.1"
schema_version = 1
authors = ["Zed Industries <support@zed.dev>", "Saicharan Kandukuri <zx@zman.dev>", "Mohit Kota <indianstar725@gmail.com>"]
repository = "https://github.com/SaicharanKandukuri/vue-2"

[language_servers.vue-two-vetur]
name = "Vue Vetur"
language = "Vue.js"
language_ids = { "Vue.js" = "vue" }
# REFACTOR is explicitly disabled, as vue-lsp does not adhere to LSP protocol for code actions with these - it
# sends back a CodeAction with neither `command` nor `edits` fields set, which is against the spec.
code_action_kinds = ["", "quickfix", "refactor.rewrite"]

[grammars.vue]
repository = "https://github.com/tree-sitter-grammars/tree-sitter-vue"
commit = "7e48557b903a9db9c38cea3b7839ef7e1f36c693"
